### ISSUE TITLE
keep ratio when resizing

### ISSUE THREAD

**Issue by giffarus** [peteruithoven/resizer#24]
good app just needing a small calculator to calculate ratios. maybe you can add a panel where we have the original resolution and calculate the wanted ratio with a factor. It will help me to make a huge picture getting a reasonable web-page size ;)

**Comment by peteruithoven** [comment]
I'm not sure I follow. So you'd have the original resolution and the desired width or height and it should give you the needed scale ratio? 
But what would you do with just the number? You don't want to actually resize an image?

**Comment by giffarus** [comment]
hum yeah, wasn't clear at all, on a rush ;p in fact my need with your tool is to quickly lower the weight of my photos without disrupting it's ratio. and to go further I need to manipulate multiple resolutions and i need to calculate for each photos the wanted dimensions (for exemple I have a 4096*3078 and a 8286*6176 and getting it into something close to the 4K resolution). 
I hope it's less confused and sorry for my writing quality

**Comment by peteruithoven** [comment]
I think we should stride towards something where you don't have to calculate these things...

What happens when you just have the Resizer **constrain** the images within 3840 x  2160 (4K) pixels? The resizer will always maintain the aspect ratio. But maybe I still don't understand what you want to achieve.
