### ISSUE TITLE
read original size

### ISSUE THREAD

**Issue by torikulhabib** [peteruithoven/resizer#27]
![gifout](https://user-images.githubusercontent.com/26135527/43969876-c760473c-9cf5-11e8-9fa6-eb7eb8e6dd5d.gif)

**Comment by torikulhabib** [comment]
i mean, resizer should read original size.

**Comment by peteruithoven** [comment]
Now you're just restating your title. To what end? And do what with that size?

**Comment by torikulhabib** [comment]
reduce as need,
future request there is option image crop.

**Comment by peteruithoven** [comment]
Why does it need the original size to "reduce as need"? 
"There"?

**Comment by torikulhabib** [comment]
just information original size. 
maybe helped some one like me

**Comment by peteruithoven** [comment]
Since I also want to support multiple images and I want to keep the visual noise / complexity to a minimum I'm not going to do this.

**Comment by wout** [comment]
In case of a single image, I would like to see this as well. Now I am forced to first look at the properties of the image.

**Comment by peteruithoven** [comment]
But why is it relevant?

**Comment by wout** [comment]
For example, in case an image is smaller than the entered dimensions, I would like to avoid scaling it up because then I will get horrible results. The image below is 300 x 300 px but there is visual reference or warning even that the given target dimensions are bigger than the source image.

![image](https://user-images.githubusercontent.com/107324/47297538-a2df4a80-d615-11e8-996e-aec7b69f06d7.png)

Optionally, you could provide a toggle to "Avoid upscaling" for example. That way the source image dimensions are irrelevant.

**Comment by peteruithoven** [comment]
Ah, but it says "max" width and height for a reason, it shouldn't upscale. Maybe I could add a little info message when images are smaller they won't be resized. 
Maybe I should add a info button somewhere where it states that it will not upscale or distort aspect ratio. Or maybe I should add those as options with checkboxes, but that would mean also implementing those, rarily used options.

**Comment by wout** [comment]
Right, I didn't actually try to resize a smaller image. As you suggest, a simple message will do the trick in this situation. And indeed, I wouldn't implement the possibility to upscale, it's not something you should endorse. :)
